### ISSUE TITLE
Add embed responsive

### ISSUE THREAD

**Issue by BrentWMiller** [skycatchfire/fire-drupal#182]
https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_responsive-embed.scss

We already have `aspect-ratio-*` classes. Just need the `embed-responsive` and `embed-responsive-item`

**Comment by BrentWMiller** [comment]
Drupal issue: https://github.com/skycatchfire/fire-drupal/issues/182

**Comment by 1forh** [comment]
https://github.com/drdogbot7/tailwindcss-responsive-embed
